// v2/src/components/FileIO.tsx
import Field from '@/components/ui/Field'
import form from '@/lib/form'
import type { IFFMpegOptionsForm } from '@/lib/types'

interface Props {
  value: IFFMpegOptionsForm['io']
  onChange: (patch: Partial<IFFMpegOptionsForm['io']>) => void
}

const control =
  'border border-gray-300 bg-white px-2 py-1.5 text-sm focus:z-10 focus:border-blue-500 ' +
  'focus:ring-1 focus:ring-blue-500 focus:outline-none dark:border-gray-600 dark:bg-gray-800 ' +
  'dark:text-gray-100'

/** Protocol select + filename, as an attached input group. */
function Row({
  id,
  label,
  value,
  placeholder,
  onChange,
}: {
  id: string
  label: string
  value: string
  placeholder: string
  onChange: (v: string) => void
}) {
  return (
    <Field label={label} htmlFor={id}>
      <div className="flex">
        <select
          aria-label={`${label} protocol`}
          className={`${control} w-24 shrink-0 rounded-l`}
          value=""
          onChange={(e) => {
            if (e.target.value) onChange(e.target.value)
          }}
        >
          <option value="">File</option>
          {form.protocols.map((p) => (
            <option key={p.name} value={p.value}>
              {p.name}
            </option>
          ))}
        </select>
        <input
          id={id}
          className={`${control} -ml-px w-full rounded-r`}
          value={value}
          placeholder={placeholder}
          onChange={(e) => onChange(e.target.value)}
        />
      </div>
    </Field>
  )
}

export default function FileIO({ value, onChange }: Props) {
  return (
    <div className="grid gap-3 sm:grid-cols-2">
      <Row
        id="io-input"
        label="Input"
        value={value.input}
        placeholder="Example: input.mp4"
        onChange={(input) => onChange({ input })}
      />
      <Row
        id="io-output"
        label="Output"
        value={value.output}
        placeholder="Example: output.mp4"
        onChange={(output) => onChange({ output })}
      />
    </div>
  )
}

// src/components/FileIO.vue
<template>
  <div class="input">
    <b-form-row>
      <!-- Input -->
      <b-col>
        <b-form-group label="Input:" label-for="input">
          <b-input-group>
            <b-form-select
              v-if="!$store.state.ffmpegdEnabled || !$store.state.wsConnected"
              class="protocol"
              v-model="protocolInput"
              @change="update('input', $event)"
            >
              <option v-for="o in protocols" :key="o.id" :value="o.value">{{o.name}}</option>
            </b-form-select>

            <b-form-input
              v-if="!$store.state.ffmpegdEnabled || !$store.state.wsConnected"
              v-model="value.input"
              :state="Boolean(value.input)"
              placeholder="Example: input.mp4"
              @input="update('input', $event)"
            ></b-form-input>

            <b-form-input
              v-else
              v-model="value.input"
              placeholder=""
              @focus="onFileFocus"
              @input="update('input', $event)"
            ></b-form-input>

            <div v-if="showFileBrowser">
              <FileBrowser v-on:file="onFileSelect" v-on:close="onClose" />
            </div>
          </b-input-group>
        </b-form-group>
      </b-col>

      <!-- Output -->
      <b-col>
        <b-form-group label="Output:" label-for="output">
          <b-input-group>
            <b-form-select
              v-if="!$store.state.ffmpegdEnabled"
              class="protocol"
              v-model="protocolOutput"
              @input="update('output', $event)"
            >
              <option v-for="o in protocols" :key="o.id" :value="o.value">{{o.name}}</option>
            </b-form-select>

            <b-form-input
              v-model="value.output"
              :state="Boolean(value.output)"
              placeholder="Example: output.mp4"
              @input="update('output', $event)"
            ></b-form-input>
          </b-input-group>
        </b-form-group>
      </b-col>
    </b-form-row>
  </div>
</template>

<script>
import form from '@/form';

import FileBrowser from '@/components/FileBrowser.vue';

const {
  protocols,
} = form;

export default {
  name: 'Input',
  components: {
    FileBrowser,
  },
  props: ['value'],
  data() {
    return {
      protocols,
      protocolInput: 'movie.mp4',
      protocolOutput: 'movie.mp4',
      showFileBrowser: false,
    };
  },
  methods: {
    update(key, value) {
      this.$emit('input', { ...this.value, [key]: value });
    },
    onFileSelect(file) {
      this.update('input', file);
      this.showFileBrowser = false;
    },
    onFileFocus() {
      this.showFileBrowser = true;
    },
    onClose() {
      this.showFileBrowser = false;
    },
  },
};
</script>

<style scoped>
.protocol {
  flex: 0 0 20% !important;
}
</style>
